Repository np-guard/models, pull requests merged in 2024-10, with the labels that each got.

#33 Generic Data Structures
  .golangci.yml
  Makefile
  README.md
  go.mod
  pkg/connection/connection.go
  pkg/connection/connectionset.go
  pkg/connection/connectionset_test.go
  pkg/connection/json.go
  pkg/ds/disjoint_sum.go
  pkg/ds/hashmap.go
  pkg/ds/hashmap_test.go
  pkg/ds/hashset.go
  pkg/ds/hashset_test.go
  pkg/ds/helpers_test.go
  pkg/ds/interfaces.go
  pkg/ds/multimap.go
  pkg/ds/multimap_test.go
  pkg/ds/product_left.go
  pkg/ds/product_test.go
  pkg/ds/triple.go
  pkg/ds/tripleset_left.go
  pkg/ds/tripleset_outer.go
  pkg/ds/tripleset_right.go
  pkg/ds/tripleset_test.go
  pkg/ds/tuples.go
  pkg/hypercube/hypercubeset.go
  pkg/hypercube/hypercubeset_test.go
  pkg/interval/interval.go
  pkg/interval/interval_test.go
  pkg/interval/intervalset.go
  pkg/interval/intervalset_test.go
  pkg/netp/common.go
  pkg/netp/icmp.go
  pkg/netp/tcpudp.go
  pkg/netset/connectionset.go
  pkg/netset/connectionset_test.go
  pkg/netset/icmpset.go
  pkg/netset/icmpset_test.go
  pkg/netset/ipblock.go
  pkg/netset/ipblock_test.go
  pkg/netset/netset.go
  pkg/netset/strings.go
  pkg/netset/tcpudpset.go
  pkg/netset/tcpudpset_test.go
  pkg/netset/transportset.go
  pkg/netset/transportset_test.go
Labels: size/XXL

#70 icmp followup: separate types for ICMP with 8-bit type/code, and with…
  pkg/connection/connection.go
  pkg/connection/json.go
  pkg/netp/icmp.go
  pkg/netset/icmpset.go
  pkg/netset/icmpset_test.go
  pkg/netset/rfcicmpset.go
  pkg/netset/tcpudpset.go
  pkg/netset/transportset.go
  pkg/netset/transportset_test.go
Labels: size/XL

#74 package reorg: remove pkg connection, rename ConnetionSet to Endpoint…
  README.md
  pkg/connection/connection.go
  pkg/netset/connectionset.go
  pkg/netset/netset.go
  pkg/netset/trafficset.go
  pkg/netset/trafficset_test.go
  pkg/netset/transportset.go
  pkg/netset/transportset_json.go
  pkg/netset/transportset_test.go
Labels: size/L

#75 New ICMP without rfc validation
  pkg/netp/icmp.go
  pkg/netset/icmpset.go
Labels: size/M

#76 IPBlock convenience functions
  pkg/interval/intervalset.go
  pkg/netset/ipblock.go
  pkg/netset/ipblock_test.go
Labels: size/L

#77 add vpe segment to data_model
  pkg/spec/data_model.go
  spec_schema.json
Labels: size/XS

#78 added AsCidr method
  pkg/netset/ipblock.go
  pkg/netset/ipblock_test.go
Labels: size/S

#81 downgrade go version to 1.22
  go.mod
Labels: size/XS
